"""Adapt Interest Parent nullable

Revision ID: 2fa310328d0d
Revises: d2f7b4704304
Create Date: 2026-05-19 15:32:50.314104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa310328d0d'
down_revision: Union[str, Sequence[str], None] = 'd2f7b4704304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'parent',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'parent',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
