"""Adapt Contact Sector key

Revision ID: d2f7b4704304
Revises: 3ee071e251b8
Create Date: 2026-05-19 15:28:46.087293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f7b4704304'
down_revision: Union[str, Sequence[str], None] = '3ee071e251b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('sector_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'contacts', ['id'])
    op.create_foreign_key(None, 'contacts', 'sectors', ['sector_id'], ['id'])
    op.drop_column('contacts', 'sector')
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'interests', ['id'])
    op.create_unique_constraint(None, 'sectors', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sectors', type_='unique')
    op.drop_constraint(None, 'interests', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.add_column('contacts', sa.Column('sector', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'sector_id')
    # ### end Alembic commands ###
